name: saeunn
favicon: null
layout_spectrum: 0.0882428614422679
typography_spectrum: 0.07184873428195715
title: 'Sæunn Thorsteinsdóttir, cellist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#63020e'
    - '#f4eeea'
    - '#944e28'
    - '#ccb6aa'
  brandStrength: 0.2702492631506175
  lightness: 0.5986621072515845
  saturation: 0.6990717591252178
  rhythmicContrast: 0.3276057590264827
purpose: []
